<?php

namespace App\StatsApi;

use DB;
use DateTimeZone;
use DateTime;
use App\Player;
use App\Stats_player;
use App\Team_subscriber;
use App\Team_user_players;

class PlayerStatsApi extends StatsApi {

/********************************************************
* saveUpdatePlayerStatsApi: Save or update championships
* @param
* @return void
********************************************************/

public static function saveUpdatePlayerStatsApi () {

  // $service = 'players/3/tournaments/stats';
  // $params = StatsApi::login();
  // StatsApi::service($service, $params);
 //$stats         = json_decode($statsApi);

	$index         = null;
	$updated       = '2017-07-12 15:58:03';
	$pointsForTeam = 0;

  $updated_at    = '2017-07-12 15:58:03';
  $points        = Stats_player::where('calculated', '1')->get();
  $stats         = json_decode(self::$statsApi);

   if (is_array($stats) || is_object($stats)) {
     
    
     foreach($stats[0]->tournament_phases as $tournament_phase) {

       foreach($tournament_phase->tournament_groups as $tournament_group) {

        foreach($tournament_group->player_stats as $player_stat) {

          $consult = Player::where('legacy_id', $player_stat->player_id)->first();

          foreach ($points as $point => $valuePoint) {

           if ( $player_stat->stat_id == $valuePoint['legacy_id'] ) {
             $stat_points = $player_stat->quantity * $valuePoint['points'];
             $total_points = $consult['points'] + $stat_points;
             $date = new DateTime($player_stat->time);

             Player::where('legacy_id', $player_stat->player_id)
             ->update([
              'points'              => $total_points,
              'legacy_stat_request' => $date
              ]);
             
             Team_user_players::where('legacy_id', $player_stat->player_id)
             ->update([
               'points' => $total_points
               ]);
           }
         }
        }
      }
    }
 }

 PlayerStatsApi::pointsForTeam();
}

/********************************************************
* pointsForTeam: Save points to user's teams
* @param
* @return void
********************************************************/

public static function pointsForTeam() {

	$points      = 0;
  $team_users = DB::table('team_user_players')->select('team_user_id')->distinct('team_user_id')->get();

  foreach ($team_users as $team_user) {
    // echo $team_user->team_user_id. "\n";
    $points = Team_user_players::where('team_user_id', $team_user->team_user_id)->sum('points');
    Team_subscriber::where('team_user_id', $team_user->team_user_id)
    ->update([
     'points' => $points
     ]);
  }
}

 static $statsApi = '[
 {
  "id": 5,
  "championship_id": 4,
  "name": "UCL 2015-2016",
  "description": "UEFA Champions League",
  "icon_updated_at": null,
  "icon_file_size": null,
  "icon_content_type": null,
  "icon_file_name": null,
  "start_date": "2015-12-04T00:00:00.000Z",
  "end_date": "2016-06-07T00:00:00.000Z",
  "is_active": false,
  "tournament_phases": [
  {
    "id": 3,
    "name": "Regular",
    "description": "Regular",
    "start_date": "2016-12-21T00:00:00.000Z",
    "end_date": "2017-06-21T00:00:00.000Z",
    "tournament_id": 5,
    "tournament_groups": [
    {
      "id": 9,
      "tournament_id": 5,
      "name": "Liga Americana",
      "description": "Liga Americana",
      "tournament_group_id": null,
      "tournament_phase_id": 3,
      "player_stats": [
      {
        "id": 1,
        "player_id": 2,
        "stat_id": 2,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 4,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 2,
          "name": "Carlos",
          "last_name": "Sanchez",
          "country_id": 1,
          "team_id": 2,
          "position_id": 2,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Barquisimeto",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 2,
        "player_id": 2,
        "stat_id": 2,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 3,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 2,
          "name": "Carlos",
          "last_name": "Sanchez",
          "country_id": 1,
          "team_id": 2,
          "position_id": 2,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Barquisimeto",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 18,
        "player_id": 6,
        "stat_id": 1,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2015-02-12T00:00:00.000Z",
        "quantity": 6,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 6,
          "name": "Esposito",
          "last_name": "Espinoza",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 19,
        "player_id": 7,
        "stat_id": 1,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2017-01-08T00:00:00.000Z",
        "quantity": 4,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 7,
          "name": "Julio",
          "last_name": "Perez",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 20,
        "player_id": 8,
        "stat_id": 1,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-02-11T00:00:00.000Z",
        "quantity": 3,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 8,
          "name": "Adrian",
          "last_name": "Diaz",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 21,
        "player_id": 8,
        "stat_id": 2,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-02-11T00:00:00.000Z",
        "quantity": 5,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 8,
          "name": "Adrian",
          "last_name": "Diaz",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 22,
        "player_id": 8,
        "stat_id": 3,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-02-11T00:00:00.000Z",
        "quantity": 6,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 8,
          "name": "Adrian",
          "last_name": "Diaz",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 23,
        "player_id": 8,
        "stat_id": 1,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-02-11T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 8,
          "name": "Adrian",
          "last_name": "Diaz",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 24,
        "player_id": 8,
        "stat_id": 2,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-02-11T00:00:00.000Z",
        "quantity": 4,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 8,
          "name": "Adrian",
          "last_name": "Diaz",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 27,
        "player_id": 9,
        "stat_id": 1,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2015-08-06T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 9,
          "name": "Anthuan",
          "last_name": "Garcia",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 28,
        "player_id": 9,
        "stat_id": 1,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2015-08-06T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 9,
          "name": "Anthuan",
          "last_name": "Garcia",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 37,
        "player_id": 1,
        "stat_id": 7,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 9,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 38,
        "player_id": 1,
        "stat_id": 8,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 4,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 39,
        "player_id": 1,
        "stat_id": 9,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 8,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 40,
        "player_id": 1,
        "stat_id": 10,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 5,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 41,
        "player_id": 1,
        "stat_id": 11,
        "team_id": 1,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 3,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 42,
        "player_id": 1,
        "stat_id": 12,
        "team_id": 1,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 43,
        "player_id": 4,
        "stat_id": 5,
        "team_id": 1,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 1,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 4,
          "name": "Jose",
          "last_name": "Morales",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 44,
        "player_id": 4,
        "stat_id": 6,
        "team_id": 1,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 9,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 4,
          "name": "Jose",
          "last_name": "Morales",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 51,
        "player_id": 2,
        "stat_id": 13,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 3,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 2,
          "name": "Carlos",
          "last_name": "Sanchez",
          "country_id": 1,
          "team_id": 2,
          "position_id": 2,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Barquisimeto",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 52,
        "player_id": 2,
        "stat_id": 14,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 2,
          "name": "Carlos",
          "last_name": "Sanchez",
          "country_id": 1,
          "team_id": 2,
          "position_id": 2,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Barquisimeto",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 53,
        "player_id": 2,
        "stat_id": 15,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 9,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 2,
          "name": "Carlos",
          "last_name": "Sanchez",
          "country_id": 1,
          "team_id": 2,
          "position_id": 2,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Barquisimeto",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 54,
        "player_id": 2,
        "stat_id": 16,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 4,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 2,
          "name": "Carlos",
          "last_name": "Sanchez",
          "country_id": 1,
          "team_id": 2,
          "position_id": 2,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Barquisimeto",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 55,
        "player_id": 2,
        "stat_id": 17,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 8,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 2,
          "name": "Carlos",
          "last_name": "Sanchez",
          "country_id": 1,
          "team_id": 2,
          "position_id": 2,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Barquisimeto",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 56,
        "player_id": 2,
        "stat_id": 18,
        "team_id": 2,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 5,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 2,
          "name": "Carlos",
          "last_name": "Sanchez",
          "country_id": 1,
          "team_id": 2,
          "position_id": 2,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Barquisimeto",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 57,
        "player_id": 2,
        "stat_id": 19,
        "team_id": 1,
        "tournament_group_id": 9,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 1,
        "date": null,
        "tournament_phase_id": 3,
        "player": {
          "id": 2,
          "name": "Carlos",
          "last_name": "Sanchez",
          "country_id": 1,
          "team_id": 2,
          "position_id": 2,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Barquisimeto",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      }
      ]
    }
    ]
  },
  {
    "id": 4,
    "name": "play-off",
    "description": "play-off",
    "start_date": "2017-06-21T00:00:00.000Z",
    "end_date": "2017-12-21T00:00:00.000Z",
    "tournament_id": 5,
    "tournament_groups": [
    {
      "id": 10,
      "tournament_id": 5,
      "name": "Liga Nacional",
      "description": "Liga Nacional",
      "tournament_group_id": null,
      "tournament_phase_id": 4,
      "player_stats": [
      {
        "id": 1,
        "player_id": 1,
        "stat_id": 1,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2015-02-12T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 2,
        "player_id": 1,
        "stat_id": 1,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-02-12T00:00:00.000Z",
        "quantity": 4,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 3,
        "player_id": 1,
        "stat_id": 1,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2015-02-12T00:00:00.000Z",
        "quantity": 5,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 4,
        "player_id": 1,
        "stat_id": 1,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2015-02-12T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 5,
        "player_id": 1,
        "stat_id": 2,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-02-12T00:00:00.000Z",
        "quantity": 4,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 6,
        "player_id": 1,
        "stat_id": 2,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2015-02-12T00:00:00.000Z",
        "quantity": 5,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 7,
        "player_id": 1,
        "stat_id": 2,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2015-02-12T00:00:00.000Z",
        "quantity": 1,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 8,
        "player_id": 1,
        "stat_id": 3,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2015-02-12T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 9,
        "player_id": 1,
        "stat_id": 3,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-02-12T00:00:00.000Z",
        "quantity": 4,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 10,
        "player_id": 1,
        "stat_id": 3,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2015-02-12T00:00:00.000Z",
        "quantity": 5,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 11,
        "player_id": 5,
        "stat_id": 1,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2017-01-08T00:00:00.000Z",
        "quantity": 4,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 5,
          "name": "Brayan",
          "last_name": "Zambrano",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 12,
        "player_id": 3,
        "stat_id": 1,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-02-11T00:00:00.000Z",
        "quantity": 5,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 3,
          "name": "Raul",
          "last_name": "Zambrano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 3,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Valencia",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 13,
        "player_id": 4,
        "stat_id": 1,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2015-08-06T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 4,
          "name": "Jose",
          "last_name": "Morales",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 14,
        "player_id": 2,
        "stat_id": 2,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 2,
          "name": "Carlos",
          "last_name": "Sanchez",
          "country_id": 1,
          "team_id": 2,
          "position_id": 2,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Barquisimeto",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 15,
        "player_id": 2,
        "stat_id": 2,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 1,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 2,
          "name": "Carlos",
          "last_name": "Sanchez",
          "country_id": 1,
          "team_id": 2,
          "position_id": 2,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Barquisimeto",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 25,
        "player_id": 9,
        "stat_id": 1,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2015-08-06T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 9,
          "name": "Anthuan",
          "last_name": "Garcia",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 26,
        "player_id": 9,
        "stat_id": 1,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2015-08-06T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 9,
          "name": "Anthuan",
          "last_name": "Garcia",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 29,
        "player_id": 9,
        "stat_id": 1,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2015-08-06T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 9,
          "name": "Anthuan",
          "last_name": "Garcia",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 30,
        "player_id": 10,
        "stat_id": 2,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 8,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 10,
          "name": "Jorge",
          "last_name": "Salcedo",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 31,
        "player_id": 10,
        "stat_id": 2,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 8,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 10,
          "name": "Jorge",
          "last_name": "Salcedo",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 32,
        "player_id": 10,
        "stat_id": 2,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 8,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 10,
          "name": "Jorge",
          "last_name": "Salcedo",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 33,
        "player_id": 10,
        "stat_id": 2,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 8,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 10,
          "name": "Jorge",
          "last_name": "Salcedo",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 34,
        "player_id": 10,
        "stat_id": 2,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 8,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 10,
          "name": "Jorge",
          "last_name": "Salcedo",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 35,
        "player_id": 1,
        "stat_id": 5,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 3,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 36,
        "player_id": 1,
        "stat_id": 6,
        "team_id": 2,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 1,
          "name": "Rafael",
          "last_name": "Marcano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Caracas",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 45,
        "player_id": 4,
        "stat_id": 7,
        "team_id": 1,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 0,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 4,
          "name": "Jose",
          "last_name": "Morales",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 46,
        "player_id": 4,
        "stat_id": 8,
        "team_id": 1,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 3,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 4,
          "name": "Jose",
          "last_name": "Morales",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 47,
        "player_id": 4,
        "stat_id": 9,
        "team_id": 1,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 4,
          "name": "Jose",
          "last_name": "Morales",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 48,
        "player_id": 4,
        "stat_id": 10,
        "team_id": 1,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 8,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 4,
          "name": "Jose",
          "last_name": "Morales",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 49,
        "player_id": 4,
        "stat_id": 11,
        "team_id": 1,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 3,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 4,
          "name": "Jose",
          "last_name": "Morales",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 50,
        "player_id": 4,
        "stat_id": 12,
        "team_id": 1,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 4,
          "name": "Jose",
          "last_name": "Morales",
          "country_id": 1,
          "team_id": 3,
          "position_id": 1,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Maracaibo",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 58,
        "player_id": 2,
        "stat_id": 20,
        "team_id": 1,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 9,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 2,
          "name": "Carlos",
          "last_name": "Sanchez",
          "country_id": 1,
          "team_id": 2,
          "position_id": 2,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Barquisimeto",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 59,
        "player_id": 2,
        "stat_id": 21,
        "team_id": 1,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 0,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 2,
          "name": "Carlos",
          "last_name": "Sanchez",
          "country_id": 1,
          "team_id": 2,
          "position_id": 2,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Barquisimeto",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 60,
        "player_id": 3,
        "stat_id": 13,
        "team_id": 1,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 3,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 3,
          "name": "Raul",
          "last_name": "Zambrano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 3,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Valencia",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 61,
        "player_id": 3,
        "stat_id": 14,
        "team_id": 1,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 3,
          "name": "Raul",
          "last_name": "Zambrano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 3,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Valencia",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 62,
        "player_id": 3,
        "stat_id": 15,
        "team_id": 1,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 3,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 3,
          "name": "Raul",
          "last_name": "Zambrano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 3,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Valencia",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 63,
        "player_id": 3,
        "stat_id": 16,
        "team_id": 1,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 3,
          "name": "Raul",
          "last_name": "Zambrano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 3,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Valencia",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 64,
        "player_id": 3,
        "stat_id": 17,
        "team_id": 1,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 3,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 3,
          "name": "Raul",
          "last_name": "Zambrano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 3,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Valencia",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 65,
        "player_id": 3,
        "stat_id": 18,
        "team_id": 1,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 3,
          "name": "Raul",
          "last_name": "Zambrano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 3,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Valencia",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 66,
        "player_id": 3,
        "stat_id": 19,
        "team_id": 1,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 3,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 3,
          "name": "Raul",
          "last_name": "Zambrano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 3,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Valencia",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 67,
        "player_id": 3,
        "stat_id": 20,
        "team_id": 1,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 2,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 3,
          "name": "Raul",
          "last_name": "Zambrano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 3,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Valencia",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      },
      {
        "id": 68,
        "player_id": 3,
        "stat_id": 21,
        "team_id": 1,
        "tournament_group_id": 10,
        "game_id": 1,
        "time": "2016-12-05T00:00:00.000Z",
        "quantity": 8,
        "date": null,
        "tournament_phase_id": 4,
        "player": {
          "id": 3,
          "name": "Raul",
          "last_name": "Zambrano",
          "country_id": 1,
          "team_id": 2,
          "position_id": 3,
          "sport_id": 1,
          "weight": 98,
          "height": 1.95,
          "birth_date": null,
          "birth_place": "Valencia",
          "left_handedness": null,
          "right_handedness": null,
          "left_footedness": null,
          "right_footedness": null,
          "avatar": "/system/uploads/icons/original/missing_players.jpeg",
          "avatar_file_name": null,
          "avatar_content_type": null,
          "avatar_file_size": null,
          "avatar_updated_at": null
        }
      }
      ]
    }
    ]
  }
  ]
}
]';
}
