<?php

namespace App\StatsApi;

Use DB;
Use App\Player;
Use App\Position;

class PlayersApi extends StatsApi {


  public static function saveUpdatePlayers () {

    //****************************************
    //Sustituir '$update_at' por el de la data
    //Sustituir championship_id
    //****************************************

    $championship_id = 1;
    $update = '2017-07-12 15:58:03';

    $players = DB::table('players')->get();

    $playerStats = json_decode(self::$allPlayers, true);

      if (is_array($playerStats) || is_object($playerStats)) {

        // foreach($json[0]->tournament_phases as $tournament_phase) {

        //   foreach($tournament_phase->tournament_groups as $tournament_group) {

          //   foreach($playerStats as $playerStat) {

          //     foreach($players as $player) {

          //       if ( ($player->legacy_id == $playerStat->id) && ($player->legacy_stat_request > $update) ) {
          //         $contador = 1;
          //         echo $playerStat->id;

          //        // DB::table('players')
          //        //    ->where('legacy_id', $playerStat['player_id'])
          //        //    ->update([
          //        //               'team_id'             => $playerStat['team_id'],
          //        //               'championship_id'     => $championship_id,
          //        //               'name'                => $playerStat['name'],
          //        //               'last_name'           => $playerStat['last_name'],
          //        //               'position'            => Position::positionPlayer($playerStat->position_id),
          //        //               'legacy_stat_request' => $update
          //        //        ]);

          //       }
          //   }
          // }
      //   }
      // }
    }
  }

static $allPlayers = '[
    {
        "id": 1,
        "name": "Rafael",
        "last_name": "Marcano",
        "country_id": 1,
        "team_id": 2,
        "position_id": 1,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Caracas",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 2,
        "name": "Carlos",
        "last_name": "Sanchez",
        "country_id": 1,
        "team_id": 2,
        "position_id": 2,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Barquisimeto",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 3,
        "name": "Raul",
        "last_name": "Zambrano",
        "country_id": 1,
        "team_id": 2,
        "position_id": 3,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Valencia",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 4,
        "name": "Jose",
        "last_name": "Morales",
        "country_id": 1,
        "team_id": 3,
        "position_id": 1,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Maracaibo",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 5,
        "name": "Brayan",
        "last_name": "Zambrano",
        "country_id": 1,
        "team_id": 3,
        "position_id": 1,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Maracaibo",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 6,
        "name": "Esposito",
        "last_name": "Espinoza",
        "country_id": 1,
        "team_id": 3,
        "position_id": 1,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Maracaibo",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 7,
        "name": "Julio",
        "last_name": "Perez",
        "country_id": 1,
        "team_id": 2,
        "position_id": 1,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Caracas",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 8,
        "name": "Adrian",
        "last_name": "Diaz",
        "country_id": 1,
        "team_id": 2,
        "position_id": 1,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Caracas",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 9,
        "name": "Anthuan",
        "last_name": "Garcia",
        "country_id": 1,
        "team_id": 3,
        "position_id": 1,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Maracaibo",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 10,
        "name": "Jorge",
        "last_name": "Salcedo",
        "country_id": 1,
        "team_id": 3,
        "position_id": 1,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Maracaibo",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 11,
        "name": "Saul",
        "last_name": "Solorzano",
        "country_id": 1,
        "team_id": 3,
        "position_id": 1,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Maracaibo",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 12,
        "name": "Michael",
        "last_name": "Camejo",
        "country_id": 1,
        "team_id": 2,
        "position_id": 1,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Caracas",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 13,
        "name": "Fabian",
        "last_name": "Florez",
        "country_id": 1,
        "team_id": 2,
        "position_id": 1,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Caracas",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 14,
        "name": "Pedro",
        "last_name": "Villoria",
        "country_id": 1,
        "team_id": 3,
        "position_id": 1,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Valencia",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 15,
        "name": "Daniel",
        "last_name": "Jimenez",
        "country_id": 1,
        "team_id": 2,
        "position_id": 1,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Maracaibo",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 16,
        "name": "Juan",
        "last_name": "Perez",
        "country_id": 1,
        "team_id": 3,
        "position_id": 1,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Caracas",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 17,
        "name": "Jorge",
        "last_name": "Manrique",
        "country_id": 1,
        "team_id": 2,
        "position_id": 1,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Barquisimeto",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 18,
        "name": "Christian",
        "last_name": "Ramos",
        "country_id": 1,
        "team_id": 3,
        "position_id": 1,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Valencia",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 19,
        "name": "Nelson",
        "last_name": "Legonia",
        "country_id": 1,
        "team_id": 3,
        "position_id": 1,
        "sport_id": 1,
        "weight": 98,
        "height": 1.95,
        "birth_date": null,
        "birth_place": "Maracaibo",
        "left_handedness": null,
        "right_handedness": null,
        "left_footedness": null,
        "right_footedness": null,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 20,
        "name": "sebastian",
        "last_name": "abreu",
        "country_id": 1,
        "team_id": 2,
        "position_id": 1,
        "sport_id": 1,
        "weight": 90,
        "height": 1.9,
        "birth_date": "1970-02-09T00:00:00.000Z",
        "birth_place": "Caracas",
        "left_handedness": false,
        "right_handedness": true,
        "left_footedness": false,
        "right_footedness": true,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 21,
        "name": "alberto",
        "last_name": "gonzalez",
        "country_id": 1,
        "team_id": 2,
        "position_id": 1,
        "sport_id": 1,
        "weight": 90,
        "height": 1.9,
        "birth_date": "1970-02-09T00:00:00.000Z",
        "birth_place": "Caracas",
        "left_handedness": false,
        "right_handedness": true,
        "left_footedness": false,
        "right_footedness": true,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 22,
        "name": "antonio",
        "last_name": "martinez",
        "country_id": 1,
        "team_id": 2,
        "position_id": 1,
        "sport_id": 1,
        "weight": 90,
        "height": 1.9,
        "birth_date": "1970-02-09T00:00:00.000Z",
        "birth_place": "Caracas",
        "left_handedness": false,
        "right_handedness": true,
        "left_footedness": false,
        "right_footedness": true,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 23,
        "name": "lucas",
        "last_name": "santana",
        "country_id": 1,
        "team_id": 2,
        "position_id": 1,
        "sport_id": 1,
        "weight": 90,
        "height": 1.9,
        "birth_date": "1970-02-09T00:00:00.000Z",
        "birth_place": "Caracas",
        "left_handedness": false,
        "right_handedness": true,
        "left_footedness": false,
        "right_footedness": true,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 24,
        "name": "sebastian",
        "last_name": "abreu",
        "country_id": 1,
        "team_id": 1,
        "position_id": 1,
        "sport_id": 1,
        "weight": 90,
        "height": 1.9,
        "birth_date": "1970-02-09T00:00:00.000Z",
        "birth_place": "Caracas",
        "left_handedness": false,
        "right_handedness": true,
        "left_footedness": false,
        "right_footedness": true,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 25,
        "name": "alberto",
        "last_name": "gonzalez",
        "country_id": 1,
        "team_id": 1,
        "position_id": 1,
        "sport_id": 1,
        "weight": 90,
        "height": 1.9,
        "birth_date": "1970-02-09T00:00:00.000Z",
        "birth_place": "Caracas",
        "left_handedness": false,
        "right_handedness": true,
        "left_footedness": false,
        "right_footedness": true,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 26,
        "name": "antonio",
        "last_name": "martinez",
        "country_id": 1,
        "team_id": 1,
        "position_id": 1,
        "sport_id": 1,
        "weight": 90,
        "height": 1.9,
        "birth_date": "1970-02-09T00:00:00.000Z",
        "birth_place": "Caracas",
        "left_handedness": false,
        "right_handedness": true,
        "left_footedness": false,
        "right_footedness": true,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    },
    {
        "id": 27,
        "name": "lucas",
        "last_name": "santana",
        "country_id": 1,
        "team_id": 1,
        "position_id": 1,
        "sport_id": 1,
        "weight": 90,
        "height": 1.9,
        "birth_date": "1970-02-09T00:00:00.000Z",
        "birth_place": "Caracas",
        "left_handedness": false,
        "right_handedness": true,
        "left_footedness": false,
        "right_footedness": true,
        "avatar": "/system/uploads/icons/original/missing_players.jpeg",
        "avatar_file_name": null,
        "avatar_content_type": null,
        "avatar_file_size": null,
        "avatar_updated_at": null
    }
]';

}

