<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;
use Carbon\Carbon;

class CompetitionsTableSeeder extends Seeder
{

  public function run()
  {
    $faker = Faker::create();

    DB::table('competitions')->insert(array(
                                            array(
                                                  'user_id'          =>  1,
                                                  'prize_id'         =>  1,
                                                  'sport_id'         =>  1,
                                                  'championship_id'  =>  1,
                                                  'name'             => 'Competition 01',
                                                  'type'             => 'PUBLIC',
                                                  'type_journal'     => '7PM',
                                                  'type_play'        => 'REGULAR',
                                                  'type_competition' => 'H2H',
                                                  'date'             => Carbon::now()->addHour(2)->toDateTimeString(),
                                                  'user_max'         =>  2,
                                                  'user_min'         =>  2,
                                                  'prize_guaranteed' =>  0,
                                                  'status'           => 'OPEN',
                                                  'entry_cost'       =>  0,
                                                  'password'         => '',
                                                  'cost_guaranteed'  =>  0,
                                                  'description'      => 'Competición de Prueba 1',
                                                  'pot'              =>  0,
                                                  'free'             =>  1,
                                                  'is_important'     => true,
                                                  'enrolled'         =>  1,
                                                  ),
                                            array(
                                                  'user_id'          =>  1,
                                                  'prize_id'         =>  1,
                                                  'sport_id'         =>  1,
                                                  'championship_id'  =>  1,
                                                  'name'             => 'Competition 02',
                                                  'type'             => 'PUBLIC',
                                                  'date'             => Carbon::now()->addDay(2)->toDateTimeString(),
                                                  'type_journal'     => '7PM',
                                                  'type_play'        => 'REGULAR',
                                                  'type_competition' => '',
                                                  'user_max'         =>  5,
                                                  'user_min'         =>  2,
                                                  'prize_guaranteed' =>  1,
                                                  'status'           => 'OPEN',
                                                  'entry_cost'       =>  100,
                                                  'password'         => '',
                                                  'cost_guaranteed'  =>  1000,
                                                  'description'      => 'Competición de Prueba 2',
                                                  'pot'              =>  0,
                                                  'free'             =>  0,
                                                  'is_important'     => false,
                                                  'enrolled'         =>  1,
                                                  ),
                                            array(
                                                  'user_id'          =>  1,
                                                  'prize_id'         =>  1,
                                                  'sport_id'         =>  1,
                                                  'championship_id'  =>  1,
                                                  'name'             => 'Competition 03',
                                                  'type'             => 'PUBLIC',
                                                  'type_journal'     => '7PM',
                                                  'type_play'        => 'REGULAR',
                                                  'type_competition' => 'H2H',
                                                  'date'             => Carbon::now()->addDay(3)->toDateTimeString(),
                                                  'user_max'         =>  2,
                                                  'user_min'         =>  2,
                                                  'prize_guaranteed' =>  0,
                                                  'status'           => 'OPEN',
                                                  'entry_cost'       =>  0,
                                                  'password'         => '',
                                                  'cost_guaranteed'  =>  0,
                                                  'description'      => 'Competición de Prueba 3',
                                                  'pot'              =>  0,
                                                  'free'             =>  1,
                                                  'is_important'     =>  false,
                                                  'enrolled'         =>  1
                                                  ),
                                            array(
                                                  'user_id'          =>  1,
                                                  'prize_id'         =>  1,
                                                  'sport_id'         =>  1,
                                                  'championship_id'  =>  1,
                                                  'name'             => 'Competition 04',
                                                  'type'             => 'PUBLIC',
                                                  'type_journal'     => '7PM',
                                                  'type_play'        => 'REGULAR',
                                                  'type_competition' => 'H2H',
                                                  'date'             => Carbon::now()->addDay(4)->toDateTimeString(),
                                                  'user_max'         =>  2,
                                                  'user_min'         =>  2,
                                                  'prize_guaranteed' =>  0,
                                                  'status'           => 'OPEN',
                                                  'entry_cost'       =>  0,
                                                  'password'         => '',
                                                  'cost_guaranteed'  =>  0,
                                                  'description'      => 'Competición de Prueba 4',
                                                  'pot'              =>  0,
                                                  'free'             =>  1,
                                                  'is_important'     =>  false,
                                                  'enrolled'         =>  1
                                                  ),
                                            array(
                                                  'user_id'          =>  1,
                                                  'prize_id'         =>  1,
                                                  'sport_id'         =>  1,
                                                  'championship_id'  =>  1,
                                                  'name'             => 'Competition 05',
                                                  'type'             => 'PUBLIC',
                                                  'type_journal'     => '7PM',
                                                  'type_play'        => 'REGULAR',
                                                  'type_competition' => 'H2H',
                                                  'date'             => Carbon::now()->addDay(5)->toDateTimeString(),
                                                  'user_max'         =>  2,
                                                  'user_min'         =>  2,
                                                  'prize_guaranteed' =>  0,
                                                  'status'           => 'OPEN',
                                                  'entry_cost'       =>  0,
                                                  'password'         => '',
                                                  'cost_guaranteed'  =>  0,
                                                  'description'      => 'Competición de Prueba 5',
                                                  'pot'              =>  0,
                                                  'free'             =>  1,
                                                  'is_important'     =>  false,
                                                  'enrolled'         =>  1
                                                  ),
                                            ));
}
}
