<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Prize_typeTableSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    DB::table('prize_types')->insert(array(
                                           array(
                                                 'prize_id'      => '1',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '1000',
                                                 'rate_win'      => '1',
                                                 'rate_range'    => '100.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '2',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100',
                                                 'rate_win'      => '1',
                                                 'rate_range'    => '70.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '2',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100',
                                                 'rate_win'      => '2',
                                                 'rate_range'    => '30.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '3',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100',
                                                 'rate_win'      => '1',
                                                 'rate_range'    => '60.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '3',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100',
                                                 'rate_win'      => '2',
                                                 'rate_range'    => '25.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '3',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100',
                                                 'rate_win'      => '3',
                                                 'rate_range'    => '15.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '4',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100',
                                                 'rate_win'      => '1',
                                                 'rate_range'    => '50.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '4',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100',
                                                 'rate_win'      => '2',
                                                 'rate_range'    => '20.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '4',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100',
                                                 'rate_win'      => '3',
                                                 'rate_range'    => '15.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '4',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100',
                                                 'rate_win'      => '4',
                                                 'rate_range'    => '10.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '4',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100',
                                                 'rate_win'      => '5',
                                                 'rate_range'    => '5.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '5',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '1',
                                                 'rate_range'    => '40.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '5',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '2',
                                                 'rate_range'    => '18.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '5',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '3',
                                                 'rate_range'    => '13.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '5',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '4',
                                                 'rate_range'    => '5.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '5',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '5',
                                                 'rate_range'    => '5.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '5',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '6',
                                                 'rate_range'    => '5.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '5',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '7',
                                                 'rate_range'    => '5.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '5',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '8',
                                                 'rate_range'    => '3.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '5',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '9',
                                                 'rate_range'    => '3.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '5',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '10',
                                                 'rate_range'    => '3.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '1',
                                                 'rate_range'    => '20.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '2',
                                                 'rate_range'    => '13.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '3',
                                                 'rate_range'    => '8.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '4',
                                                 'rate_range'    => '7.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '5',
                                                 'rate_range'    => '6.00',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '6',
                                                 'rate_range'    => '2.20',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '7',
                                                 'rate_range'    => '2.20',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '8',
                                                 'rate_range'    => '2.20',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '9',
                                                 'rate_range'    => '2.20',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '10',
                                                 'rate_range'    => '2.20',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '11',
                                                 'rate_range'    => '1.30',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '12',
                                                 'rate_range'    => '1.30',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '13',
                                                 'rate_range'    => '1.30',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '14',
                                                 'rate_range'    => '1.30',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '15',
                                                 'rate_range'    => '1.30',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '16',
                                                 'rate_range'    => '1.30',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '17',
                                                 'rate_range'    => '1.30',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '18',
                                                 'rate_range'    => '1.30',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '19',
                                                 'rate_range'    => '1.30',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '20',
                                                 'rate_range'    => '1.30',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '21',
                                                 'rate_range'    => '0.90',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '22',
                                                 'rate_range'    => '0.90',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '23',
                                                 'rate_range'    => '0.90',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '24',
                                                 'rate_range'    => '0.90',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '25',
                                                 'rate_range'    => '0.90',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '26',
                                                 'rate_range'    => '0.90',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '27',
                                                 'rate_range'    => '0.90',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '28',
                                                 'rate_range'    => '0.90',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '29',
                                                 'rate_range'    => '0.90',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '30',
                                                 'rate_range'    => '0.90',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '31',
                                                 'rate_range'    => '0.80',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '32',
                                                 'rate_range'    => '0.80',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '33',
                                                 'rate_range'    => '0.80',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '34',
                                                 'rate_range'    => '0.80',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '35',
                                                 'rate_range'    => '0.80',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '36',
                                                 'rate_range'    => '0.80',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '37',
                                                 'rate_range'    => '0.80',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '38',
                                                 'rate_range'    => '0.80',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '39',
                                                 'rate_range'    => '0.80',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '40',
                                                 'rate_range'    => '0.80',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '41',
                                                 'rate_range'    => '0.60',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '42',
                                                 'rate_range'    => '0.60',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '43',
                                                 'rate_range'    => '0.60',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '44',
                                                 'rate_range'    => '0.60',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '45',
                                                 'rate_range'    => '0.60',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '46',
                                                 'rate_range'    => '0.40',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '47',
                                                 'rate_range'    => '0.40',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '48',
                                                 'rate_range'    => '0.40',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '49',
                                                 'rate_range'    => '0.40',
                                                 'equitable'     => '1',
                                                 ),
                                           array(
                                                 'prize_id'      => '6',
                                                 'range'         => '',
                                                 'rate'          => 0,
                                                 'winning'       => '100000',
                                                 'rate_win'      => '50',
                                                 'rate_range'    => '0.40',
                                                 'equitable'     => '1',
                                                 ),
                                           ));
}
}
