<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;

class Stats_PlayersTableSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    // $faker = Faker::create();

    // DB::table('stats_players')->insert(array(
    //                                          array(
    //                                                'name'           => 'Hit',
    //                                                'legacy_id'       =>  1,
    //                                                'description'     => 'Hit',
    //                                                'sport_id'        =>  1,
    //                                                'calculated'      =>  1,
    //                                                'points'          =>  3,
    //                                                ),
    //                                          array(
    //                                                'name'           => '2B',
    //                                                'legacy_id'       =>  2,
    //                                                'description'     => 'Segunda Base',
    //                                                'sport_id'        =>  1,
    //                                                'calculated'      =>  1,
    //                                                'points'          =>  5.5,
    //                                                ),
    //                                          array(
    //                                                'name'           => '3B',
    //                                                'legacy_id'       =>  3,
    //                                                'description'     => 'Tercera Base',
    //                                                'sport_id'        =>  1,
    //                                                'calculated'      =>  1,
    //                                                'points'          =>  8,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'HR',
    //                                                'legacy_id'       =>  4,
    //                                                'description'     => '',
    //                                                'sport_id'        =>  1,
    //                                                'calculated'      =>  1,
    //                                                'points'          =>  10,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'CI',
    //                                                'legacy_id'       =>  5,
    //                                                'description'     => 'Center Fielder',
    //                                                'sport_id'        =>  1,
    //                                                'calculated'      =>  1,
    //                                                'points'          =>  3,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'CA',
    //                                                'legacy_id'       =>  6,
    //                                                'description'     => '',
    //                                                'sport_id'        =>  1,
    //                                                'calculated'      =>  1,
    //                                                'points'          =>  2,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'BB',
    //                                                'legacy_id'       =>  7,
    //                                                'description'     => '',
    //                                                'sport_id'        =>  1,
    //                                                'calculated'      =>  1,
    //                                                'points'          =>  3,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'BR',
    //                                                'legacy_id'       =>  8,
    //                                                'description'     => '',
    //                                                'sport_id'        =>  1,
    //                                                'calculated'      =>  1,
    //                                                'points'          =>  5,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'GP',
    //                                                'legacy_id'       =>  9,
    //                                                'description'     => '',
    //                                                'sport_id'        =>  1,
    //                                                'calculated'      =>  1,
    //                                                'points'          =>  3,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'OR',
    //                                                'legacy_id'       =>  10,
    //                                                'description'     => '',
    //                                                'sport_id'        =>  1,
    //                                                'calculated'      =>  1,
    //                                                'points'          => -3,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'IP',
    //                                                'legacy_id'       => 11,
    //                                                'description'     => '',
    //                                                'sport_id'        => 1,
    //                                                'calculated'      => 1,
    //                                                'points'          => 4.5,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'K',
    //                                                'legacy_id'       => 12,
    //                                                'description'     => '',
    //                                                'sport_id'        => 1,
    //                                                'calculated'      => 1,
    //                                                'points'          => 4,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'G',
    //                                                'legacy_id'       => 13,
    //                                                'description'     => '',
    //                                                'sport_id'        => 1,
    //                                                'calculated'      => 1,
    //                                                'points'          => 10,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'CL',
    //                                                'legacy_id'       => 14,
    //                                                'description'     => '',
    //                                                'sport_id'        => 1,
    //                                                'calculated'      => 1,
    //                                                'points'          => -3.6,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'H',
    //                                                'legacy_id'       => 15,
    //                                                'description'     => '',
    //                                                'sport_id'        => 1,
    //                                                'calculated'      => 1,
    //                                                'points'          => -1.2,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'BB',
    //                                                'legacy_id'       => 16,
    //                                                'description'     => '',
    //                                                'sport_id'        => 1,
    //                                                'calculated'      => 1,
    //                                                'points'          => -1.2,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'GP',
    //                                                'legacy_id'       => 17,
    //                                                'description'     => '',
    //                                                'sport_id'        => 1,
    //                                                'calculated'      => 1,
    //                                                'points'          => -1.2,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'L',
    //                                                'legacy_id'       => 18,
    //                                                'description'     => '',
    //                                                'sport_id'        => 1,
    //                                                'calculated'      => 1,
    //                                                'points'          => -5,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'G',
    //                                                'legacy_id'       => 19,
    //                                                'description'     => 'Goal',
    //                                                'sport_id'        => 2,
    //                                                'calculated'      => 1,
    //                                                'points'          => 12,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'A',
    //                                                'legacy_id'       => 20,
    //                                                'description'     => 'Asistencia',
    //                                                'sport_id'        => 2,
    //                                                'calculated'      => 1,
    //                                                'points'          => 7,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'S',
    //                                                'legacy_id'       => 21,
    //                                                'description'     => 'Shot',
    //                                                'sport_id'        => 2,
    //                                                'calculated'      => 1,
    //                                                'points'          => 1.5,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'FR',
    //                                                'legacy_id'       => 22,
    //                                                'description'     => 'Falta Recibida',
    //                                                'sport_id'        => 2,
    //                                                'calculated'      => 1,
    //                                                'points'          => 0.5,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'FC',
    //                                                'legacy_id'       => 23,
    //                                                'description'     => 'Falta Cometida',
    //                                                'sport_id'        => 2,
    //                                                'calculated'      => 1,
    //                                                'points'          => 0.5,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'BR',
    //                                                'legacy_id'       => 24,
    //                                                'description'     => 'Balones Recuperados, solo defensa',
    //                                                'sport_id'        => 2,
    //                                                'calculated'      => 1,
    //                                                'points'          => 1,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'TA',
    //                                                'legacy_id'       => 25,
    //                                                'description'     => 'Tarjeta Amarilla',
    //                                                'sport_id'        => 2,
    //                                                'calculated'      => 1,
    //                                                'points'          => -2,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'TR',
    //                                                'legacy_id'       => 26,
    //                                                'description'     => 'Tarjeta Roja',
    //                                                'sport_id'        => 2,
    //                                                'calculated'      => 1,
    //                                                'points'          => -4,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'SHOA',
    //                                                'legacy_id'       => 27,
    //                                                'description'     => 'Clean Sheet, solo arquero',
    //                                                'sport_id'        => 2,
    //                                                'calculated'      => 1,
    //                                                'points'          => 10,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'SHOD',
    //                                                'legacy_id'       => 28,
    //                                                'description'     => 'Clean Sheet, solo defensa',
    //                                                'sport_id'        => 2,
    //                                                'calculated'      => 1,
    //                                                'points'          => 3,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'PF',
    //                                                'legacy_id'       => 29,
    //                                                'description'     => 'Penalti Fallado',
    //                                                'sport_id'        => 2,
    //                                                'calculated'      => 1,
    //                                                'points'          => -5,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'PD',
    //                                                'legacy_id'       => 30,
    //                                                'description'     => 'Penalti Defendido, solo arquero',
    //                                                'sport_id'        => 2,
    //                                                'calculated'      => 1,
    //                                                'points'          => 5,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'W',
    //                                                'legacy_id'       => 31,
    //                                                'description'     => 'Victoria, arquero',
    //                                                'sport_id'        => 2,
    //                                                'calculated'      => 1,
    //                                                'points'          => 5,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'SA',
    //                                                'legacy_id'       => 32,
    //                                                'description'     => 'Atrapada, arquero',
    //                                                'sport_id'        => 2,
    //                                                'calculated'      => 1,
    //                                                'points'          => 2,
    //                                                ),
    //                                          array(
    //                                                'name'           => 'GA',
    //                                                'legacy_id'       => 33,
    //                                                'description'     => 'Goles en Contra, arquero',
    //                                                'sport_id'        => 2,
    //                                                'calculated'      => 1,
    //                                                'points'          => -2.5,
    //                                                )
    //                                          ));
  }
}
